### ISSUE TITLE
If ESC pressed app not starting anymore with 'electron .'

### ISSUE THREAD

**Issue by vasyl-shumskyi** [tommoor/electron-lets-move#8]
I just tried to test `lets-move` with default settings on unpackaged app. 

Not sure if this is known behavior, but when  ESC pressed it breaks app starting via `npm start` Start script `electron .` seems to be broken.

I think ESC calls 'Move To Application' button instead of 'Don't Move' Button by default.

```
$ npm start

> My-App@1.0.0 start /app/path
> electron .

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn /app/path/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

Reinstalling electron helps to fix this issue

`npm install electron -D`

**Comment by vasyl-shumskyi** [comment]
Fix was easy as below. 
[Official documentation](https://electron.atom.io/docs/api/dialog/) states: 

> `cancelId` Integer (optional) - The index of the button to be used to cancel the dialog, via the Esc key. By default this is assigned to the first button with “cancel” or “no” as the label. If no such labeled buttons exist and this option is not set, 0 will be used as the return value or callback response. This option is ignored on Windows.
